CREATE DATABASE "Formula1"

CREATE TABLE IF NOT EXISTS "Engineers" (
                                           "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
                                           "specialty" VARCHAR(50) NOT NULL,
    "yearofexperience" INTEGER NOT NULL,
    "id_member" INTEGER not null,
    PRIMARY KEY("id")
    );

CREATE TABLE IF NOT EXISTS "TeamMembers" (
                                             "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
                                             "name" VARCHAR(50) NOT NULL,
    "age" INTEGER NOT NULL,
    "wage" DECIMAL,
    PRIMARY KEY("id")
    );

CREATE TABLE IF NOT EXISTS "TeamBosses" (
                                            "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
                                            "bonus" DECIMAL,
                                            "id_member" INTEGER not null,
                                            PRIMARY KEY("id")
    );

CREATE TABLE IF NOT EXISTS "Drivers" (
                                         "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
                                         "carnumber" INTEGER NOT NULL,
                                         "handicap" DECIMAL NOT NULL,
                                         "pointsonseason" INTEGER NOT NULL,
                                         "id_member" INTEGER not null,
                                         PRIMARY KEY("id")
    );

CREATE TABLE IF NOT EXISTS "Teams" (
                                       "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
                                       "name" VARCHAR(20) NOT NULL,
    "citizenship" VARCHAR(20) NOT NULL,
    "pointsonseason" INTEGER NOT NULL,
    "id_teamboss" INTEGER NOT NULL,
    PRIMARY KEY("id")
    );

CREATE TABLE IF NOT EXISTS "Cars" (
                                      "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
                                      "model" VARCHAR(20) NOT NULL,
    "hp" INTEGER NOT NULL,
    "aerodynamic" DECIMAL NOT NULL,
    "id_driver" INTEGER NOT NULL,
    "id_team" INTEGER NOT NULL,
    PRIMARY KEY("id")
    );

CREATE TABLE IF NOT EXISTS "Races" (
                                       "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
                                       "name" VARCHAR(50) NOT NULL,
    "country" VARCHAR(2) NOT NULL,
    PRIMARY KEY("id")
    );

CREATE TABLE IF NOT EXISTS "RacesResults" (
                                              "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
                                              "id_driver" INTEGER NOT NULL,
                                              "positions" INTEGER NOT NULL,
                                              "points" INTEGER NOT NULL,
                                              "id_race" INTEGER,
                                              PRIMARY KEY("id")
    );

CREATE TABLE IF NOT EXISTS "Circuits" (
    "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "name" VARCHAR(50) NOT NULL,
    "country" VARCHAR(2) NOT NULL,
    PRIMARY KEY("id")
)


ALTER TABLE "Drivers"
    ADD FOREIGN KEY("id_member") REFERENCES "TeamMembers"("id")
        ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "TeamBosses"
    ADD FOREIGN KEY("id_member") REFERENCES "TeamMembers"("id")
        ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "Engineers"
    ADD FOREIGN KEY("id_member") REFERENCES "TeamMembers"("id")
        ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "Cars"
    ADD FOREIGN KEY("id_driver") REFERENCES "Drivers"("id")
        ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "Cars"
    ADD FOREIGN KEY("id_team") REFERENCES "Teams"("id")
        ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "RacesResults"
    ADD FOREIGN KEY("id_race") REFERENCES "Races"("id")
        ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "RacesResults"
    ADD FOREIGN KEY("id_driver") REFERENCES "Drivers"("id")
        ON UPDATE CASCADE ON DELETE CASCADE;

alter table "Teams"
    add foreign KEY("id_teamboss") references "TeamBosses"("id")
        on update cascade on delete cascade;

